version: '3.8'

services:
  mgmt-vibe:
    build: .
    image: mgmt-vibe:v1.0.0
    container_name: mgmt-vibe-production
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DEMO_MODE=false
      - PERFORMANCE_MONITORING=true
      - MEMORY_OPTIMIZATION=true
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    networks:
      - mgmt-vibe-network

networks:
  mgmt-vibe-network:
    driver: bridge