name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run check

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format:check

      - name: Build
        run: npm run build

      - name: Smoke tests
        run: npm run smoke

      - name: Generate SBOM
        run: |
          npm install -g @cyclonedx/cdxgen
          cdxgen -t npm -o dist/sbom.json

      - name: Security scan
        uses: github/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_YAML: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            !dist/**/*.log
          retention-days: 30

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: dist/sbom.json
          retention-days: 90

  e2e:
    runs-on: ubuntu-latest
    needs: build-and-smoke
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install system dependencies for Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 libatk-bridge2.0-0 libxkbcommon0 libdrm2 libgbm1 \
            libasound2 fonts-liberation libxshmfence1 libx11-6 libxcomposite1 \
            libxdamage1 libxfixes3 libxi6 libgtk-3-0 libpangocairo-1.0-0 \
            libxrandr2 libxrender1 ca-certificates

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run E2E (headless)
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "false"
        run: npm run e2e

      - name: Run Navigation E2E (headless)
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "false"
        run: npm run nav:e2e

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-screenshots
          path: demo/assets/screens
